[package]
name = "ekore"
version = "0.1.0"
edition = "2021"
description = "EKO expressions"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
num = "0.4.1"
float-cmp = "0.9.0"
bibliothek = { version = "0.2.0" }
katexit = "0.1.4"
hashbrown = "0.14"
