[package]
name = "ekore"
version = "0.1.0"
edition = "2021"
description = "EKO expressions"
license = "GPL-3.0-or-later"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "../katex-header.html" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
float-cmp = "0.9.0"
hashbrown = "0.14"
