# Setup
title: eko
tagline: "Evolutionary Kernel Operators"
description: >
  Evolutionary Kernel Operators:<br>
  <em>yet another PDF evolution library</em>.
url: "https://n3pdf.github.io"
baseurl: "/eko"
permalink: /:categories/:title

# API data

jekyll_get_json:
  - data: latest_release
    json: "https://api.github.com/repos/N3PDF/eko/releases/latest"

# About and contact
author:
  name: "Alessandro Candido, Felix Hekhorn, Giacomo Magni"
  url: "http://n3pdf.mi.infn.it"

github:
  repo: "https://github.com/N3PDF/eko"
  api: "https://api.github.com/repos/N3PDF/eko"

# Gems
plugins:
  - jekyll-get-json
  - jekyll-paginate
  - jekyll-gist
