# Setup
title: eko
tagline: "Evolutionary Kernel Operators"
description: >
  Evolutionary Kernel Operators:<br>
  yet another PDF evolution library.
url: "https://n3pdf.github.io"
baseurl: "/eko"
permalink: /:categories/:title

# About and contact
author:
  name: "Alessandro Candido, Felix Hekhorn, Giacomo Magni"
  url: "http://n3pdf.mi.infn.it"

github:
  repo: "https://github.com/N3PDF/eko"
  api: "https://api.github.com/repos/N3PDF/eko"

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
