[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "eko"
version = "0.0.0"
description = "Evolution Kernel Operator"
authors = ["A. Candido", "S. Carrazza <stefano.carrazza@cern.ch>", "J. Cruz-Martinez", "F. Hekhorn", "G. Magni"]
classifiers = [
"Programming Language :: Python",
"Programming Language :: Python :: 3",
"Topic :: Scientific/Engineering",
"Topic :: Scientific/Engineering :: Physics",
"License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]
repository = "https://github.com/N3PDF/eko"
include = [ "doc/source/img/Logo.png" ]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
numpy = "^1.20.0"
scipy = "^1.7.3"
PyYAML = "^6.0"
lz4 = "^3.1.10"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
isort = "^5.10.1"
pylint = "^2.12.2"
pre-commit = "^2.16.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-env = "^0.6.2"
# benchmark
ekomark = { path = "benchmarks/", develop = true }
Sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-bibtex = "^2.4.1"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
dirty = true

[tool.poetry-dynamic-versioning.substitution]
files = ["src/eko/__init__.py"]

[tool.poe.tasks]
# until https://github.com/numba/numba/pull/5660 is confirmed we need to deactivate numba prior running
test = {shell="NUMBA_DISABLE_JIT=1 pytest tests"}
lint = "pylint src/*/*.py -E"
lint-warnings = "pylint src/*/*.py --exit-zero"
sandbox = "python benchmarks/runners/sandbox.py"
# navigator = "navigator"
black = "black ."
isort = "isort . --skip env"
format = ["black", "isort"]

[tool.pytest.ini_options]
#norecursedirs = benchmarks/aux
testpaths = ['tests/']#, 'benchmarks/runners/']
python_files = ['test_*.py', 'benchmark_*.py', 'regression.py']
python_classes = ['Test*', 'Benchmark*']
python_functions = ['test_*', 'benchmark_*']
addopts = [
  '--cov=eko',
  '--cov-report=html',
  '--cov-report=xml',
  '--strict-markers',
]
env = ["NUMBA_DISABLE_JIT=1"]

[tool.isort]
profile = "black"
