[build-system]
requires = ['setuptools >= 40.9.0', 'wheel', 'packutil']
build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
#norecursedirs = benchmarks/aux
testpaths = ['tests/']#, 'benchmarks/runners/']
python_files = ['test_*.py', 'benchmark_*.py', 'regression.py']
python_classes = ['Test*', 'Benchmark*']
python_functions = ['test_*', 'benchmark_*']
addopts = [
  '--cov=eko',
  '--cov-report=html',
  '--cov-report=xml',
  '--strict-markers',
]
env = ["NUMBA_DISABLE_JIT=1"]
