[package]
name = "dekoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4_flex = "0.10.0"
ndarray = "0.15.6"
ndarray-npy = "0.8.1"
serde = { version = "1.0.162", features = ["derive"] }
serde_yaml = "0.9.21"
