[package]
name = "eko"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "../katex-header.html" ]

[lib]
name = "ekors"
crate-type = ["cdylib"]

[dependencies]
num = "0.4.1"
ekore = { version = "0.1.0", path = "../ekore" }
