//! List of References (autogenerated on 2025-02-24T12:35:24.669515).

#[allow(non_snake_case)]
/// The Three loop splitting functions in QCD: The Nonsinglet case
///
/// Moch, S. and Vermaseren, J. A. M. and Vogt, A.
///
/// Published in: Nucl. Phys. B688 (2004), 101-134
///
/// e-Print: [hep-ph/0403192](https://arxiv.org/abs/hep-ph/0403192)
///
/// DOI: [10.1016/j.nuclphysb.2004.03.030](https:dx.doi.org/10.1016/j.nuclphysb.2004.03.030)
pub fn Moch2004pa() {}

#[allow(non_snake_case)]
/// The Three-loop splitting functions in QCD: The Singlet case
///
/// Vogt, A. and Moch, S. and Vermaseren, J. A. M.
///
/// Published in: Nucl. Phys. B691 (2004), 129-181
///
/// e-Print: [hep-ph/0404111](https://arxiv.org/abs/hep-ph/0404111)
///
/// DOI: [10.1016/j.nuclphysb.2004.04.024](https:dx.doi.org/10.1016/j.nuclphysb.2004.04.024)
pub fn Vogt2004mw() {}

#[allow(non_snake_case)]
/// Programs for computing the logarithm of the gamma function, and the digamma function, for complex argument
///
/// K.S. Kölbig
///
/// Published in: Computer Physics Communications 4 (1972), 221 - 226
///
///
///
/// DOI: [https://doi.org/10.1016/0010-4655(72)90012-4](https://doi.org/10.1016/0010-4655(72)90012-4)
pub fn KOLBIG1972221() {}

#[allow(non_snake_case)]
/// Multi‐precision Laplace transform inversion
///
/// Abate, J. and Valkó, P.
///
/// Published in: International Journal for Numerical Methods in Engineering 60 (2004), 979 - 993
///
///
///
/// DOI: [10.1002/nme.995](https:dx.doi.org/10.1002/nme.995)
pub fn Abate() {}

#[allow(non_snake_case)]
/// Resummations of Transverse Momentum Distributions
///
/// Muselli, Claudio
///
/// Published as PhD thesis at Università degli studi di Milano, Dipartimento di Fisica (2017)
///
///
///
/// DOI: [10.13130/muselli-claudio_phd2017-12-01](https:dx.doi.org/10.13130/muselli-claudio_phd2017-12-01)
pub fn MuselliPhD() {}

#[allow(non_snake_case)]
/// Efficient evolution of unpolarized and polarized parton distributions with QCD-PEGASUS
///
/// Vogt, A.
///
/// Published in: Comput. Phys. Commun. 170 (2005), 65--92
///
/// e-Print: [hep-ph/0408244](https://arxiv.org/abs/hep-ph/0408244)
///
/// DOI: [10.1016/j.cpc.2005.03.103](https:dx.doi.org/10.1016/j.cpc.2005.03.103)
pub fn Vogt2004ns() {}

#[allow(non_snake_case)]
/// Intrinsic charm in a matched general-mass scheme
///
/// Ball, Richard D. and Bertone, Valerio and Bonvini, Marco and Forte, Stefano and Groth Merrild, Patrick and Rojo, Juan and Rottoli, Luca
///
/// Published in: Phys. Lett. B 754 (2016), 49--58
///
/// e-Print: [1510.00009](https://arxiv.org/abs/1510.00009)
///
/// DOI: [10.1016/j.physletb.2015.12.077](https:dx.doi.org/10.1016/j.physletb.2015.12.077)
pub fn Ball2015tna() {}

#[allow(non_snake_case)]
/// Charm electroproduction viewed in the variable flavor number scheme versus fixed order perturbation theory
///
/// Buza, M. and Matiounine, Y. and Smith, J. and van Neerven, W. L.
///
/// Published in: Eur. Phys. J. C 1 (1998), 301--320
///
/// e-Print: [hep-ph/9612398](https://arxiv.org/abs/hep-ph/9612398)
///
/// DOI: [10.1007/BF01245820](https:dx.doi.org/10.1007/BF01245820)
pub fn Buza1996wv() {}

#[allow(non_snake_case)]
/// The Gluonic Operator Matrix Elements at O(alpha(s)**2) for DIS Heavy Flavor Production
///
/// Bierenbaum, Isabella and Blumlein, Johannes and Klein, Sebastian
///
/// Published in: Phys. Lett. B 672 (2009), 401--406
///
/// e-Print: [0901.0669](https://arxiv.org/abs/0901.0669)
///
/// DOI: [10.1016/j.physletb.2009.01.057](https:dx.doi.org/10.1016/j.physletb.2009.01.057)
pub fn Bierenbaum2009zt() {}

#[allow(non_snake_case)]
/// Next-to-leading order radiative parton model analysis of polarized deep inelastic lepton - nucleon scattering
///
/// Gluck, M. and Reya, E. and Stratmann, M. and Vogelsang, W.
///
/// Published in: Phys. Rev. D 53 (1996), 4775--4786
///
/// e-Print: [hep-ph/9508347](https://arxiv.org/abs/hep-ph/9508347)
///
/// DOI: [10.1103/PhysRevD.53.4775](https:dx.doi.org/10.1103/PhysRevD.53.4775)
pub fn Gluck1995yr() {}

#[allow(non_snake_case)]
/// Parton distribution functions with QED corrections
///
/// Carrazza, Stefano
///
/// Published as PhD thesis at Milan U. (2015)
///
/// e-Print: [1509.00209](https://arxiv.org/abs/1509.00209)
///
/// DOI: [10.13130/carrazza-stefano_phd2015-07-06](https:dx.doi.org/10.13130/carrazza-stefano_phd2015-07-06)
pub fn Carrazza2015dea() {}

#[allow(non_snake_case)]
/// QED corrections to the Altarelli-Parisi splitting functions
///
/// de Florian, Daniel and Sborlini, Germán F. R. and Rodrigo, Germán
///
/// Published in: Eur. Phys. J. C 76 (2016), 282
///
/// e-Print: [1512.00612](https://arxiv.org/abs/1512.00612)
///
/// DOI: [10.1140/epjc/s10052-016-4131-8](https:dx.doi.org/10.1140/epjc/s10052-016-4131-8)
pub fn deFlorian2015ujt() {}

#[allow(non_snake_case)]
/// Two-loop QED corrections to the Altarelli-Parisi splitting functions
///
/// de Florian, Daniel and Sborlini, Germán F. R. and Rodrigo, Germán
///
/// Published in: JHEP 10 (2016), 056
///
/// e-Print: [1606.02887](https://arxiv.org/abs/1606.02887)
///
/// DOI: [10.1007/JHEP10(2016)056](https:dx.doi.org/10.1007/JHEP10(2016)056)
pub fn deFlorian2016gvk() {}

#[allow(non_snake_case)]
/// Four-Loop Non-Singlet Splitting Functions in the Planar Limit and Beyond
///
/// Moch, S. and Ruijl, B. and Ueda, T. and Vermaseren, J. A. M. and Vogt, A.
///
/// Published in: JHEP 10 (2017), 041
///
/// e-Print: [1707.08315](https://arxiv.org/abs/1707.08315)
///
/// DOI: [10.1007/JHEP10(2017)041](https:dx.doi.org/10.1007/JHEP10(2017)041)
pub fn Moch2017uml() {}

#[allow(non_snake_case)]
/// Four-loop splitting functions in QCD - the gluon-gluon case -
///
/// Falcioni, G. and Herzog, F. and Moch, S. and Pelloni, A. and Vogt, A.
///
/// Published in: Phys. Lett. B 860 (2025), 139194
///
/// e-Print: [2410.08089](https://arxiv.org/abs/2410.08089)
///
/// DOI: [10.1016/j.physletb.2024.139194](https:dx.doi.org/10.1016/j.physletb.2024.139194)
pub fn Falcioni2024qpd() {}

#[allow(non_snake_case)]
/// Four-loop splitting functions in QCD - The quark-to-gluon case
///
/// Falcioni, G. and Herzog, F. and Moch, S. and Pelloni, A. and Vogt, A.
///
/// Published in: Phys. Lett. B 856 (2024), 138906
///
/// e-Print: [2404.09701](https://arxiv.org/abs/2404.09701)
///
/// DOI: [10.1016/j.physletb.2024.138906](https:dx.doi.org/10.1016/j.physletb.2024.138906)
pub fn Falcioni2024xyt() {}

#[allow(non_snake_case)]
/// Four-loop splitting functions in QCD - The quark-quark case
///
/// Falcioni, G. and Herzog, F. and Moch, S. and Vogt, A.
///
/// Published in: Phys. Lett. B 842 (2023), 137944
///
/// e-Print: [2302.07593](https://arxiv.org/abs/2302.07593)
///
/// DOI: [10.1016/j.physletb.2023.137944](https:dx.doi.org/10.1016/j.physletb.2023.137944)
pub fn Falcioni2023luc() {}

#[allow(non_snake_case)]
/// Four-loop splitting functions in QCD - The gluon-to-quark case
///
/// Falcioni, G. and Herzog, F. and Moch, S. and Vogt, A.
///
/// Published in: Phys. Lett. B 846 (2023), 138215
///
/// e-Print: [2307.04158](https://arxiv.org/abs/2307.04158)
///
/// DOI: [10.1016/j.physletb.2023.138215](https:dx.doi.org/10.1016/j.physletb.2023.138215)
pub fn Falcioni2023vqq() {}
