//! List of References (autogenerated on 2024-05-30T12:57:15.459698).

#[allow(non_snake_case)]
/// The Three loop splitting functions in QCD: The Nonsinglet case
///
/// Moch, S. and Vermaseren, J. A. M. and Vogt, A.
///
/// Published in: Nucl. Phys. B688 (2004), 101-134
///
/// e-Print: [hep-ph/0403192](https://arxiv.org/abs/hep-ph/0403192)
///
/// DOI: [10.1016/j.nuclphysb.2004.03.030](https:dx.doi.org/10.1016/j.nuclphysb.2004.03.030)
pub fn Moch2004pa() {}

#[allow(non_snake_case)]
/// The Three-loop splitting functions in QCD: The Singlet case
///
/// Vogt, A. and Moch, S. and Vermaseren, J. A. M.
///
/// Published in: Nucl. Phys. B691 (2004), 129-181
///
/// e-Print: [hep-ph/0404111](https://arxiv.org/abs/hep-ph/0404111)
///
/// DOI: [10.1016/j.nuclphysb.2004.04.024](https:dx.doi.org/10.1016/j.nuclphysb.2004.04.024)
pub fn Vogt2004mw() {}

#[allow(non_snake_case)]
/// Programs for computing the logarithm of the gamma function, and the digamma function, for complex argument
///
/// K.S. Kölbig
///
/// Published in: Computer Physics Communications 4 (1972), 221 - 226
///
///
///
/// DOI: [https://doi.org/10.1016/0010-4655(72)90012-4](https://doi.org/10.1016/0010-4655(72)90012-4)
pub fn KOLBIG1972221() {}

#[allow(non_snake_case)]
/// Multi‐precision Laplace transform inversion
///
/// Abate, J. and Valkó, P.
///
/// Published in: International Journal for Numerical Methods in Engineering 60 (2004), 979 - 993
///
///
///
/// DOI: [10.1002/nme.995](https:dx.doi.org/10.1002/nme.995)
pub fn Abate() {}

#[allow(non_snake_case)]
/// Resummations of Transverse Momentum Distributions
///
/// Muselli, Claudio
///
/// Published as PhD thesis at Università degli studi di Milano, Dipartimento di Fisica (2017)
///
///
///
/// DOI: [10.13130/muselli-claudio_phd2017-12-01](https:dx.doi.org/10.13130/muselli-claudio_phd2017-12-01)
pub fn MuselliPhD() {}

#[allow(non_snake_case)]
/// Efficient evolution of unpolarized and polarized parton distributions with QCD-PEGASUS
///
/// Vogt, A.
///
/// Published in: Comput. Phys. Commun. 170 (2005), 65--92
///
/// e-Print: [hep-ph/0408244](https://arxiv.org/abs/hep-ph/0408244)
///
/// DOI: [10.1016/j.cpc.2005.03.103](https:dx.doi.org/10.1016/j.cpc.2005.03.103)
pub fn Vogt2004ns() {}
