//! List of References (autogenerated on 2023-11-29T18:07:41.518255).

/// The Three loop splitting functions in QCD: The Nonsinglet case
///
/// Moch, S. and Vermaseren, J. A. M. and Vogt, A.
///
/// Published in: Nucl. Phys. B688 (2004), 101-134
///
/// e-Print: [hep-ph/0403192](https://arxiv.org/abs/hep-ph/0403192)
///
/// DOI: [10.1016/j.nuclphysb.2004.03.030](https:dx.doi.org/10.1016/j.nuclphysb.2004.03.030)
pub fn Moch2004pa() {}

/// The Three-loop splitting functions in QCD: The Singlet case
///
/// Vogt, A. and Moch, S. and Vermaseren, J. A. M.
///
/// Published in: Nucl. Phys. B691 (2004), 129-181
///
/// e-Print: [hep-ph/0404111](https://arxiv.org/abs/hep-ph/0404111)
///
/// DOI: [10.1016/j.nuclphysb.2004.04.024](https:dx.doi.org/10.1016/j.nuclphysb.2004.04.024)
pub fn Vogt2004mw() {}

/// Programs for computing the logarithm of the gamma function, and the digamma function, for complex argument
///
/// K.S. Kölbig
///
/// Published in: Computer Physics Communications 4 (1972), 221 - 226
///
///
///
/// DOI: [https://doi.org/10.1016/0010-4655(72)90012-4](https://doi.org/10.1016/0010-4655(72)90012-4)
pub fn KOLBIG1972221() {}

/// Multi‐precision Laplace transform inversion
///
/// Abate, J. and Valkó, P.
///
/// Published in: International Journal for Numerical Methods in Engineering 60 (2004), 979 - 993
///
///
///
/// DOI: [10.1002/nme.995](https:dx.doi.org/10.1002/nme.995)
pub fn Abate() {}
