name: Deploy Crates

on:
  push:
    # TODO: remove branches
    branches: ["*"]
    tags:
      - "*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
      - name: Install task runner
        run: pip install poethepoet
      - name: Bump versions
        run: |
          poetry install --only version
          poe bump-version
      - name: Publish crates
        run: |
          jq '.[]' release.json | xargs -I _ cargo publish -p _ --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
