name: isolated benchmarks

on: push

jobs:
  isobench:
    name: 🏝️ Isolated Benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # tags needed for dynamic versioning
          fetch-depth: 0
      - name: Install Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Use Python 3.14
        run: poetry env use ${{ env.pythonLocation }}/bin/python
      - name: Install project
        run: |
          poetry install --no-interaction --with test -E mark -E box
      - name: Install task runner
        run: pip install poethepoet
      - name: Lint with pylint
        run: |
          # Search for actual errors
          poe lint
          # For warnings instead return always zero
          poe lint-warnings
      - name: Test with pytest
        run: |
          poe bench-iso
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          flags: isobench
          name: codecov-umbrella
          fail_ci_if_error: false
