# A single CI script with github workflow.
name: LHA Benchmarks (Rust)

on:
  push:
    branches-ignore:
      - "*"
    tags:
  pull_request:
    types:
      - closed
      - ready_for_review
      - review_requested
  workflow_dispatch:

jobs:
  lhabench:
    name: LHA paper Benchmarks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} 🐍
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          installer-parallel: true
      - name: Install project
        run: |
          poetry install --no-interaction --with test -E mark -E box
      - name: Install task runner
        run: pip install poethepoet
      - name: Run benchmark
        run: |
          ./rustify.sh
          poe compile
          poe lha -m "nnlo and sv"
          poe lha -m "ffns_pol and sv"
