name: deploy

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    uses: ./.github/workflows/python-poetry-pypi-with-data.yml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      poetry-extras: "-E mark -E box"
      data-version: "v2"
      data-download: "./tests/data/assets.sh"
