name: deploy

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write

jobs:
  publish:
    uses: ./.github/workflows/python-poetry-pypi-with-data.yml
    permissions:
      id-token: write
      contents: read
    with:
      poetry-extras: "-E mark -E box"
      data-version: "v2"
      data-download: "./tests/data/assets.sh"
