name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    #if: startsWith(github.event.ref, 'refs/tags')

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Setup Python 🐍
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        pip install -e .
    - name: Package the distribution
      run: |
        # package the pure python wheel
        pip wheel . -w dist --no-deps
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
