name: Python unit tests

on: push

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
      fail-fast: false

    uses: ./.github/workflows/python-poetry-tests-with-data.yml
    with:
      python-version: ${{ matrix.python-version }}
      poetry-extras: "-E mark -E box"
      data-version: "v2"
      data-download: "./tests/data/assets.sh"
