name: Rust unit tests

on:
  push:
    # TODO: remove branches
    branches: ["*"]

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
    #   - name: Install and configure Poetry
    #     uses: snok/install-poetry@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            override: true
      - name: Install task runner
        run: pip install poethepoet
      - name: Run Rust unit tests
        run: |
          #   poetry install
          poe rtest
