name: Python unit tests

on: push

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false

    uses: EKO/workflows/.github/workflows/python-poetry-tests-with-data.yml@read-legacy
    with:
      python-version: ${{ matrix.python-version }}
      poetry-extras: "-E mark -E box"
      data-version: "v1"
      data-download: "./tests/data/assets.sh"
