name: unit tests

on:
  push:
    branches-ignore:
      - "*docs*"

jobs:
  py37:
    runs-on: ubuntu-latest

    steps:
      - uses: N3PDF/workflows/.github/workflows/python-poetry-setup.yml@main
        with:
          python-version: "3.7"
          poetry-extras: "-E mark"
      - uses: N3PDF/workflows/.github/workflows/python-poetry-tests.yml@main
        with:
          python-version: "3.7"

  py38:
    runs-on: ubuntu-latest

    steps:
      - uses: N3PDF/workflows/.github/workflows/python-poetry-setup.yml@main
        with:
          python-version: "3.8"
          poetry-extras: "-E mark"
      - uses: N3PDF/workflows/.github/workflows/python-poetry-tests.yml@main
        with:
          python-version: "3.8"

  py39:
    runs-on: ubuntu-latest

    steps:
      - uses: N3PDF/workflows/.github/workflows/python-poetry-setup.yml@main
        with:
          python-version: "3.9"
          poetry-extras: "-E mark"
      - uses: N3PDF/workflows/.github/workflows/python-poetry-tests.yml@main
        with:
          python-version: "3.9"
