name: Rust unit tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get test data
        id: cache-test-data
        uses: actions/cache@v4
        with:
          path: test-data
          key: test-data-v2
      - name: Download test data
        if: steps.cache-test-data.outputs.cache-hit != 'true'
        run: |
          ./tests/data/assets.sh
      - uses: actions/setup-python@v5
      - name: Install task runner
        run: pip install poethepoet
      - name: Run fmt
        run: |
          poe fmtcheck
      - name: Run clippy
        run: |
          poe clippy
      - name: Install gsl
        run: sudo apt-get install libgsl0-dev
      - name: Run Rust unit tests
        run: |
          poe rtest
